require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
#$RNFirebaseAsStaticFramework = true
#$FirebaseSDKVersion = '9.3.0'

platform :ios, '12.0'

target 'BidFood' do
  config = use_native_modules!
#   use_frameworks!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()
  
#  pod 'Firebase/Auth'
#  pod 'Firebase/Firestore'
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  use_flipper!({ 'Flipper' => '0.74.0' })
  # use_flipper!({ 'Flipper' => '0.95.0' })
  post_install do |installer|
    react_native_post_install(installer)
  end
end

